### ISSUE TITLE
Actionsflow will get stuck in the "Setup act" phase

### ISSUE THREAD

**Issue by stu43005** [actionsflow/setup-act-for-actionsflow#1]
After the v1.1.3 update, the "Setup act" stage will get stuck and fail in 6 hours

![image](https://user-images.githubusercontent.com/1288549/105620216-6c688980-5e35-11eb-9dc8-78178465b4e6.png)

![image](https://user-images.githubusercontent.com/1288549/105620255-e8fb6800-5e35-11eb-86ae-4309fed338e6.png)

**Comment by lucasew** [comment]
I am having the same [problem](https://github.com/lucasew/flows/runs/1764176816?check_suite_focus=true) from few days.

I've tried updating the yaml actions definition from the template repo but it's still hanging.

BTW other jobs are queueing for more time than normal.

**Comment by lucasew** [comment]
The first-run survey was introduced at [v0.2.19](https://github.com/nektos/act/releases/tag/v0.2.19) by https://github.com/nektos/act/pull/483.

[Downgrading it](https://github.com/lucasew/flows/commit/d4049d7446b01eb0c3344467f4522d51c2f8ced9) to 0.2.18 [solves](https://github.com/lucasew/flows/runs/1764258235?check_suite_focus=true) the problem.

**Comment by theowenyoung** [comment]
Thanks for the report, sorry for the late reply, I have downgraded act to 0.2.18, and I'll fix the install issue later.

**Comment by theowenyoung** [comment]
@stu43005 @lucasew Hi, I have fixed the problem([v1](https://github.com/actionsflow/setup-act-for-actionsflow/releases/tag/v1) has been alias to the latest released version)). You can remove the spec version 0.2.18, 0.2.19 is worth to upgrade.
